### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [BPI-SINOVOIP/RPi.GPIO#6]
How do I install this ?

**Comment by Caminero5** [comment]
There's a good [explanation](https://wiki.banana-pi.org/Getting_Started_with_R2#Install_RPi.GPIO) here

**Comment by hexzhen3x7** [comment]
> How do I install this ?


git clone https://github.com/bpi-codehunterz-world/RPi.GPIO # ISSUE GCC-10 COMPILER 
sudo chmod 777 -R ./*
me=$(whoami)
sudo chown $me -hR ./*
cd RPi.GPIO
sudo apt-get install -y python3-dev python3-pip python3-venv
sudo apt-get install -y python2-dev python2-pip 
sudo apt-get install -y python-dev python-pip 
sudo python3 -m pip install -U pip
sudo python2 -m pip install -U pip
sudo python -m pip install -U pip
sudo python3 -m pip install setuptools disutils wheel
sudo python2 -m pip install setuptools disutils wheel
sudo python -m pip install setuptools disutils wheel
sudo python3 setup.py install
sudo python2 setup.py install
sudo python setup.py install
sudo pip3 install . 
sudo pip3 install .  --break-system-packages
sudo python -m pip install .
sudo python2 -m pip install .
sudo python3 crea*
echo -e "Console > Installation Should be finished!"

**Comment by GeorgeFlorian** [comment]
So funny to get an answer after 5+ years.

I've since ditched the Banana PI as it is very different from the RPI.
